"""add is_agent to person

Revision ID: 059f4168241b
Revises: 63a72d994f4c
Create Date: 2026-02-08 13:21:56.300342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059f4168241b'
down_revision: Union[str, None] = '63a72d994f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_stakeholder', 'rol',
               existing_type=sa.VARCHAR(),
               comment='eigenaar|betrokken|adviseur|indiener',
               existing_comment='eigenaar|betrokken|adviseur',
               existing_nullable=False)
    op.alter_column('organisatie_eenheid', 'type',
               existing_type=sa.VARCHAR(),
               comment='e.g. ministerie|directoraat_generaal|directie|dienst|bureau|afdeling|team',
               existing_comment='e.g. ministerie|directoraat_generaal|directie|afdeling|team',
               existing_nullable=False)
    op.add_column('person', sa.Column('is_agent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_agent')
    op.alter_column('organisatie_eenheid', 'type',
               existing_type=sa.VARCHAR(),
               comment='e.g. ministerie|directoraat_generaal|directie|afdeling|team',
               existing_comment='e.g. ministerie|directoraat_generaal|directie|dienst|bureau|afdeling|team',
               existing_nullable=False)
    op.alter_column('node_stakeholder', 'rol',
               existing_type=sa.VARCHAR(),
               comment='eigenaar|betrokken|adviseur',
               existing_comment='eigenaar|betrokken|adviseur|indiener',
               existing_nullable=False)
    # ### end Alembic commands ###
