"""add sender_id to notification

Revision ID: 0ace27e4dc4b
Revises: 8aa16e702ec9
Create Date: 2026-02-08 13:54:26.028235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ace27e4dc4b'
down_revision: Union[str, None] = '8aa16e702ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notification', 'person', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'sender_id')
    # ### end Alembic commands ###
