"""add sender_id to notification

Revision ID: 0ace27e4dc4b
Revises: 8aa16e702ec9
Create Date: 2026-02-08 13:54:26.028235

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ace27e4dc4b'
down_revision: str | None = '8aa16e702ec9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notification', 'person', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'sender_id')
    # ### end Alembic commands ###
