"""add organisatie_eenheid_id and parent_id to task

Revision ID: 2442ad1cfef7
Revises: 61c6590ad60c
Create Date: 2026-02-08 16:40:44.408683

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2442ad1cfef7'
down_revision: str | None = '61c6590ad60c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mention', 'mention_type',
               existing_type=sa.VARCHAR(length=16),
               comment='person|organisatie|node|task|tag',
               existing_comment='person|node|task|tag',
               existing_nullable=False)
    op.alter_column('motie_import', 'status',
               existing_type=sa.VARCHAR(),
               comment='pending|imported|reviewed|rejected|out_of_scope',
               existing_comment='pending|imported|reviewed|rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('task', sa.Column('organisatie_eenheid_id', sa.UUID(), nullable=True))
    op.add_column('task', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(
        op.f('ix_task_organisatie_eenheid_id'),
        'task', ['organisatie_eenheid_id'], unique=False,
    )
    op.create_index(
        op.f('ix_task_parent_id'),
        'task', ['parent_id'], unique=False,
    )
    op.create_foreign_key(
        None, 'task', 'task',
        ['parent_id'], ['id'], ondelete='CASCADE',
    )
    op.create_foreign_key(
        None, 'task', 'organisatie_eenheid',
        ['organisatie_eenheid_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_parent_id'), table_name='task')
    op.drop_index(op.f('ix_task_organisatie_eenheid_id'), table_name='task')
    op.drop_column('task', 'parent_id')
    op.drop_column('task', 'organisatie_eenheid_id')
    op.alter_column('motie_import', 'status',
               existing_type=sa.VARCHAR(),
               comment='pending|imported|reviewed|rejected',
               existing_comment='pending|imported|reviewed|rejected|out_of_scope',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('mention', 'mention_type',
               existing_type=sa.VARCHAR(length=16),
               comment='person|node|task|tag',
               existing_comment='person|organisatie|node|task|tag',
               existing_nullable=False)
    # ### end Alembic commands ###
