"""initial

Revision ID: 2ebdc49f0f07
Revises:
Create Date: 2026-02-07 12:11:58.361258

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ebdc49f0f07"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corpus_node",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "node_type",
            sa.String(),
            nullable=False,
            comment="dossier|doel|instrument|beleidskader|maatregel|politieke_input",
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default="actief", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edge_type",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("label_nl", sa.String(), nullable=False),
        sa.Column("label_en", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_custom", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("naam", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("afdeling", sa.String(), nullable=True),
        sa.Column("functie", sa.String(), nullable=True),
        sa.Column("oidc_subject", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("oidc_subject"),
    )
    op.create_table(
        "team",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("naam", sa.String(), nullable=False),
        sa.Column("beschrijving", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "absence",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("substitute_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reden", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["substitute_id"], ["person.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beleidskader",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "scope", sa.String(), nullable=False, comment="nationaal|eu|internationaal"
        ),
        sa.Column("geldig_van", sa.Date(), nullable=True),
        sa.Column("geldig_tot", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.String(),
            nullable=False,
            comment="politiek|organisatorisch|operationeel",
        ),
        sa.Column("bron", sa.String(), nullable=True),
        sa.Column("meetbaar", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("streefwaarde", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dossier",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fase",
            sa.String(),
            nullable=False,
            comment="verkenning|beleidsvorming|uitvoering|evaluatie",
        ),
        sa.Column("eigenaar", sa.String(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "prioriteit",
            sa.String(),
            server_default="normaal",
            nullable=False,
            comment="laag|normaal|hoog|kritiek",
        ),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edge",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("from_node_id", sa.UUID(), nullable=False),
        sa.Column("to_node_id", sa.UUID(), nullable=False),
        sa.Column("edge_type_id", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["edge_type_id"], ["edge_type.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["from_node_id"], ["corpus_node.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["to_node_id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrument",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.String(),
            nullable=False,
            comment="wetgeving|subsidie|voorlichting|handhaving|overig",
        ),
        sa.Column("rechtsgrondslag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maatregel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kosten_indicatie", sa.String(), nullable=True),
        sa.Column("verwacht_effect", sa.Text(), nullable=True),
        sa.Column("uitvoerder", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node_stakeholder",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "rol", sa.String(), nullable=False, comment="eigenaar|betrokken|adviseur"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["node_id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "politieke_input",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.String(),
            nullable=False,
            comment="coalitieakkoord|motie|kamerbrief|toezegging|amendement",
        ),
        sa.Column(
            "referentie", sa.String(), nullable=True, comment="e.g. kamerstuknummer"
        ),
        sa.Column("datum", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.String(),
            server_default="open",
            nullable=False,
            comment="open|in_behandeling|afgedaan",
        ),
        sa.ForeignKeyConstraint(["id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.String(),
            server_default="open",
            nullable=False,
            comment="open|in_progress|done|cancelled",
        ),
        sa.Column(
            "priority",
            sa.String(),
            server_default="normaal",
            nullable=False,
            comment="laag|normaal|hoog|kritiek",
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["assignee_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["corpus_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_member",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "rol",
            sa.String(),
            server_default="lid",
            nullable=False,
            comment="lid|coordinator",
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "person_id"),
    )
    op.create_table(
        "activity",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "event_type",
            sa.String(),
            nullable=False,
            comment="node.created|node.updated|edge.created|edge.deleted|task.created|task.assigned|task.completed|stakeholder.added",
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("node_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("edge_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["edge_id"], ["edge.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["corpus_node.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.String(),
            nullable=False,
            comment="task_assigned|task_overdue|node_updated|edge_created|coverage_needed",
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("related_node_id", sa.UUID(), nullable=True),
        sa.Column("related_task_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["related_node_id"], ["corpus_node.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["related_task_id"], ["task.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_table("activity")
    op.drop_table("team_member")
    op.drop_table("task")
    op.drop_table("politieke_input")
    op.drop_table("node_stakeholder")
    op.drop_table("maatregel")
    op.drop_table("instrument")
    op.drop_table("edge")
    op.drop_table("dossier")
    op.drop_table("doel")
    op.drop_table("beleidskader")
    op.drop_table("absence")
    op.drop_table("team")
    op.drop_table("person")
    op.drop_table("edge_type")
    op.drop_table("corpus_node")
    # ### end Alembic commands ###
