"""add document_url to motie_import

Revision ID: 348de7d0a505
Revises: 9126f2f4f7fb
Create Date: 2026-02-08 12:32:40.520414

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '348de7d0a505'
down_revision: str | None = '9126f2f4f7fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motie_import', sa.Column('document_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motie_import', 'document_url')
    # ### end Alembic commands ###
