"""add mention table

Revision ID: 61c6590ad60c
Revises: 0ace27e4dc4b
Create Date: 2026-02-08 14:31:51.713857

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61c6590ad60c"
down_revision: str | None = "0ace27e4dc4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mention",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "source_type",
            sa.String(length=32),
            nullable=False,
            comment="node|task|organisatie|notification",
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "mention_type",
            sa.String(length=16),
            nullable=False,
            comment="person|node|task|tag",
        ),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mention_source", "mention", ["source_id", "source_type"], unique=False
    )
    op.create_index(
        "ix_mention_target", "mention", ["target_id", "mention_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mention_target", table_name="mention")
    op.drop_index("ix_mention_source", table_name="mention")
    op.drop_table("mention")
    # ### end Alembic commands ###
