"""add api_key to person

Revision ID: 8aa16e702ec9
Revises: 059f4168241b
Create Date: 2026-02-08 13:29:56.249216

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8aa16e702ec9'
down_revision: str | None = '059f4168241b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'api_key')
    # ### end Alembic commands ###
