"""add tag node_tag motie_import suggested_edge tables

Revision ID: 8ad772f71cc6
Revises: c804f70f9817
Create Date: 2026-02-08 11:52:41.219998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ad772f71cc6'
down_revision: Union[str, None] = 'c804f70f9817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tag.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('motie_import',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('zaak_id', sa.String(), nullable=False),
    sa.Column('zaak_nummer', sa.String(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('onderwerp', sa.String(), nullable=False),
    sa.Column('bron', sa.String(), nullable=False, comment='tweede_kamer|eerste_kamer'),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False, comment='pending|imported|reviewed|rejected'),
    sa.Column('corpus_node_id', sa.UUID(), nullable=True),
    sa.Column('llm_samenvatting', sa.Text(), nullable=True),
    sa.Column('matched_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_api_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_node_id'], ['corpus_node.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zaak_id')
    )
    op.create_table('node_tag',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['corpus_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'tag_id', name='uq_node_tag')
    )
    op.create_table('suggested_edge',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('motie_import_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False, comment='pending|approved|rejected'),
    sa.Column('edge_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edge.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edge_type_id'], ['edge_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['motie_import_id'], ['motie_import.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_node_id'], ['corpus_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_edge')
    op.drop_table('node_tag')
    op.drop_table('motie_import')
    op.drop_table('tag')
    # ### end Alembic commands ###
