"""add indieners and document_tekst to motie_import

Revision ID: 9126f2f4f7fb
Revises: 8ad772f71cc6
Create Date: 2026-02-08 12:14:54.282398

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9126f2f4f7fb"
down_revision: str | None = "8ad772f71cc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "motie_import",
        sa.Column("indieners", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("motie_import", sa.Column("document_tekst", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("motie_import", "document_tekst")
    op.drop_column("motie_import", "indieners")
    # ### end Alembic commands ###
