"""add probleem effect beleidsoptie node types

Revision ID: c804f70f9817
Revises: c3d4e5f6g7h8
Create Date: 2026-02-08 09:32:12.375563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c804f70f9817'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beleidsoptie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='verkennend', nullable=False, comment='verkennend|voorgesteld|gekozen|afgewezen'),
    sa.Column('kosten_indicatie', sa.String(), nullable=True),
    sa.Column('verwacht_effect', sa.Text(), nullable=True),
    sa.Column('risico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['corpus_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effect',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False, comment='output|outcome|impact'),
    sa.Column('indicator', sa.String(), nullable=True),
    sa.Column('streefwaarde', sa.String(), nullable=True),
    sa.Column('meetbaar', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['corpus_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probleem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('urgentie', sa.String(), server_default='normaal', nullable=False, comment='laag|normaal|hoog|kritiek'),
    sa.Column('bron', sa.String(), nullable=True),
    sa.Column('impact_beschrijving', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['corpus_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('corpus_node', 'node_type',
               existing_type=sa.VARCHAR(),
               comment='dossier|doel|instrument|beleidskader|maatregel|politieke_input|probleem|effect|beleidsoptie',
               existing_comment='dossier|doel|instrument|beleidskader|maatregel|politieke_input',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corpus_node', 'node_type',
               existing_type=sa.VARCHAR(),
               comment='dossier|doel|instrument|beleidskader|maatregel|politieke_input',
               existing_comment='dossier|doel|instrument|beleidskader|maatregel|politieke_input|probleem|effect|beleidsoptie',
               existing_nullable=False)
    op.drop_table('probleem')
    op.drop_table('effect')
    op.drop_table('beleidsoptie')
    # ### end Alembic commands ###
